### PR TITLE
Stash

### PR DESCRIPTION
**Pull request by JoshArmi**

### CODE REVIEW

**Review by rickfoxcroft — APPROVED** [review]
Great work @JoshArmi ! 🇭🇲

**Review by bryan-yu — APPROVED** [review]
Awesome dude! Failing test here

Screen Shot 2021-02-10 at 11 34 44 am

**Comment by rickfoxcroft** [comment]
Build is failing. Looks like you may need to extend the timeout on your tests or adjust approach.

**Comment by t04glovern** [comment]
Hello Joshua. could you please provide more comments?

**Comment by rickfoxcroft** [comment]
> Kudos, SonarCloud Quality Gate passed!
> 
> [Bug](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=VULNERABILITY)
> [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=SECURITY_HOTSPOT)
> [Code Smell](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=JoshArmi_CQRServerless&pullRequest=2&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=JoshArmi_CQRServerless&pullRequest=2) No Coverage information
> [](https://sonarcloud.io/component_measures?id=JoshArmi_CQRServerless&pullRequest=2&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=JoshArmi_CQRServerless&pullRequest=2&metric=new_duplicated_lines_density&view=list)

Very impressive! ☝️

**Comment by rickfoxcroft** [comment]
> Hello Joshua. could you please provide more comments?

@t04glovern PR seems to be lacking a description.

**Comment by bryan-yu** [comment]
Hey Josh, got some tips to help with good pr descriptions: https://frontside.com/blog/2020-7-reasons-for-good-pull-request-descriptions/. Love your work!

**Pull request closed without merging**
